name: Deploy Saul Server

on:
  workflow_dispatch:


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_DO_TOKEN: ${{ secrets.DO_TOKEN }}
  TF_VAR_MYSQL_DB: ${{ secrets.MYSQL_DB }}
  TF_VAR_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  TF_VAR_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  TF_VAR_MYSQL_USER: ${{ secrets.MYSQL_USER }}
  TF_VAR_DOMAIN: ${{ secrets.DOMAIN }}
  TF_VAR_USER_EMAIL: ${{ secrets.USER_EMAIL }}

  
jobs:
  terraform-apply:
      runs-on: ubuntu-lates
      steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.9.8
            terraform_wrapper: false

        - name: Create SSH keys from secrets
          run: |
            mkdir keys
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/saul_server
            echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/saul_server.pub
            chmod 777 ./keys/saul_server
            chmod 777 ./keys/saul_server.pub

        - name: Terraform Init
          run: terraform init

        - name: Terraform fromat
          run: terraform fmt

        - name: Terraform validate
          run: terraform validate

        - name: Terraform destroy
          run: terraform destroy --auto-approve
